[package]
name = "vaporeon"
version = "0.1.0"
edition = "2021"

[dependencies]
bus = "2.4.1"
clap = { version = "4.5.27", features = ["derive"] }
crossbeam-channel = "0.5.13"
env_logger = "0.11.5"
log = "0.4.22"
serde = "1.0.217"
serde_derive = "1.0.217"
toml = "0.8.19"
